-- AlterTable
ALTER TABLE "EventDescription" ADD COLUMN     "AITimeout" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Resource" ADD COLUMN     "AITimeout" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "ResourceType" ADD COLUMN     "AITimeout" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
