import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/components/auth/AuthProvider";
import NotificationProvider from "@/components/notification/NotificationProvider";
import AuthProtecter from "@/components/auth/AuthProtector";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full w-full antialiased bg-white`}
    >
      <body className="w-full h-full flex flex-col">
        <Script src="https://accounts.google.com/gsi/client" strategy="afterInteractive" />
        <NotificationProvider>
          <AuthProvider>
            <AuthProtecter>
              {children}
            </AuthProtecter>
          </AuthProvider>
        </NotificationProvider>
      </body>
    </html>
  );
}
